insert into ciudad(nombre, id_provincia) values('San Lorenzo'	, 1 );
insert into ciudad(nombre, id_provincia) values('Eloy Alfaro'	, 1 );
insert into ciudad(nombre, id_provincia) values('Rioverde'	, 1 );
insert into ciudad(nombre, id_provincia) values('Esmeraldas'	, 1 );
insert into ciudad(nombre, id_provincia) values('Muisne'	, 1 );
insert into ciudad(nombre, id_provincia) values('Atacames'	, 1 );
insert into ciudad(nombre, id_provincia) values('Quinindé'	, 1 );
insert into ciudad(nombre, id_provincia) values('Tulcán'	, 2 );
insert into ciudad(nombre, id_provincia) values('Mira'	, 2 );
insert into ciudad(nombre, id_provincia) values('Espejo'	, 2 );
insert into ciudad(nombre, id_provincia) values('Montúfar'	, 2 );
insert into ciudad(nombre, id_provincia) values('San Pedro de Huaca'	, 2 );
insert into ciudad(nombre, id_provincia) values('Bolívar (Carchi)'	, 2 );
insert into ciudad(nombre, id_provincia) values('Ibarra'	, 3 );
insert into ciudad(nombre, id_provincia) values('San Miguel de Urcuquí'	, 3 );
insert into ciudad(nombre, id_provincia) values('Cotacachi'	, 3 );
insert into ciudad(nombre, id_provincia) values('Antonio Ante'	, 3 );
insert into ciudad(nombre, id_provincia) values('Otavalo'	, 3 );
insert into ciudad(nombre, id_provincia) values('Pimampiro'	, 3 );
insert into ciudad(nombre, id_provincia) values('Sucumbíos'	, 4 );
insert into ciudad(nombre, id_provincia) values('Gonzalo Pizarro'	, 4 );
insert into ciudad(nombre, id_provincia) values('Cascales'	, 4 );
insert into ciudad(nombre, id_provincia) values('Lago Agrio'	, 4 );
insert into ciudad(nombre, id_provincia) values('Putumayo'	, 4 );
insert into ciudad(nombre, id_provincia) values('Cuyabeno'	, 4 );
insert into ciudad(nombre, id_provincia) values('Shushufindi'	, 4 );
insert into ciudad(nombre, id_provincia) values('Pedernales'	, 5 );
insert into ciudad(nombre, id_provincia) values('Chone'	, 5 );
insert into ciudad(nombre, id_provincia) values('Flavio Alfaro'	, 5 );
insert into ciudad(nombre, id_provincia) values('El Carmen'	, 5 );
insert into ciudad(nombre, id_provincia) values('Jama'	, 5 );
insert into ciudad(nombre, id_provincia) values('San Vicente'	, 5 );
insert into ciudad(nombre, id_provincia) values('Sucre'	, 5 );
insert into ciudad(nombre, id_provincia) values('Tosagua'	, 5 );
insert into ciudad(nombre, id_provincia) values('Rocafuerte'	, 5 );
insert into ciudad(nombre, id_provincia) values('Junín'	, 5 );
insert into ciudad(nombre, id_provincia) values('Bolívar (Manabí)'	, 5 );
insert into ciudad(nombre, id_provincia) values('Pichincha'	, 5 );
insert into ciudad(nombre, id_provincia) values('Portoviejo'	, 5 );
insert into ciudad(nombre, id_provincia) values('Jaramijó'	, 5 );
insert into ciudad(nombre, id_provincia) values('Manta'	, 5 );
insert into ciudad(nombre, id_provincia) values('Montecristi'	, 5 );
insert into ciudad(nombre, id_provincia) values('Santa Ana'	, 5 );
insert into ciudad(nombre, id_provincia) values('Jipijapa'	, 5 );
insert into ciudad(nombre, id_provincia) values('Veinticuatro de Mayo'	, 5 );
insert into ciudad(nombre, id_provincia) values('Olmedo (Manabí)'	, 5 );
insert into ciudad(nombre, id_provincia) values('Puerto López'	, 5 );
insert into ciudad(nombre, id_provincia) values('Paján'	, 5 );
insert into ciudad(nombre, id_provincia) values('La Concordia'	, 6 );
insert into ciudad(nombre, id_provincia) values('Santo Domingo'	, 6 );
insert into ciudad(nombre, id_provincia) values('Puerto Quito'	, 7 );
insert into ciudad(nombre, id_provincia) values('Pedro Vicente Maldonado'	, 7 );
insert into ciudad(nombre, id_provincia) values('San Miguel de Los Bancos'	, 7 );
insert into ciudad(nombre, id_provincia) values('Distrito Metropolitano de Quito'	, 7 );
insert into ciudad(nombre, id_provincia) values('Pedro Moncayo'	, 7 );
insert into ciudad(nombre, id_provincia) values('Cayambe'	, 7 );
insert into ciudad(nombre, id_provincia) values('Rumiñahui'	, 7 );
insert into ciudad(nombre, id_provincia) values('Mejía'	, 7 );
insert into ciudad(nombre, id_provincia) values('El Chaco'	, 8 );
insert into ciudad(nombre, id_provincia) values('Quijos'	, 8 );
insert into ciudad(nombre, id_provincia) values('Archidona'	, 8 );
insert into ciudad(nombre, id_provincia) values('Tena'	, 8 );
insert into ciudad(nombre, id_provincia) values('Carlos Julio Arosemena Tola'	, 8 );
insert into ciudad(nombre, id_provincia) values('Loreto'	, 9 );
insert into ciudad(nombre, id_provincia) values('Francisco de Orellana'	, 9 );
insert into ciudad(nombre, id_provincia) values('La Joya de los Sachas'	, 9 );
insert into ciudad(nombre, id_provincia) values('Aguarico'	, 9 );
insert into ciudad(nombre, id_provincia) values('Mera'	, 10 );
insert into ciudad(nombre, id_provincia) values('Santa Clara'	, 10 );
insert into ciudad(nombre, id_provincia) values('Arajuno'	, 10 );
insert into ciudad(nombre, id_provincia) values('Pastaza'	, 10 );
insert into ciudad(nombre, id_provincia) values('Buena Fe'	, 11 );
insert into ciudad(nombre, id_provincia) values('Valencia'	, 11 );
insert into ciudad(nombre, id_provincia) values('Quevedo'	, 11 );
insert into ciudad(nombre, id_provincia) values('Quinsaloma'	, 11 );
insert into ciudad(nombre, id_provincia) values('Palenque'	, 11 );
insert into ciudad(nombre, id_provincia) values('Mocache'	, 11 );
insert into ciudad(nombre, id_provincia) values('Ventanas'	, 11 );
insert into ciudad(nombre, id_provincia) values('Vinces'	, 11 );
insert into ciudad(nombre, id_provincia) values('Baba'	, 11 );
insert into ciudad(nombre, id_provincia) values('Puebloviejo'	, 11 );
insert into ciudad(nombre, id_provincia) values('Urdaneta'	, 11 );
insert into ciudad(nombre, id_provincia) values('Babahoyo'	, 11 );
insert into ciudad(nombre, id_provincia) values('Montalvo'	, 11 );
insert into ciudad(nombre, id_provincia) values('Sigchos'	, 12 );
insert into ciudad(nombre, id_provincia) values('La Maná'	, 12 );
insert into ciudad(nombre, id_provincia) values('Latacunga'	, 12 );
insert into ciudad(nombre, id_provincia) values('Saquisilí'	, 12 );
insert into ciudad(nombre, id_provincia) values('Pujilí'	, 12 );
insert into ciudad(nombre, id_provincia) values('Pangua'	, 12 );
insert into ciudad(nombre, id_provincia) values('Salcedo'	, 12 );
insert into ciudad(nombre, id_provincia) values('Guaranda'	, 13 );
insert into ciudad(nombre, id_provincia) values('Las Naves'	, 13 );
insert into ciudad(nombre, id_provincia) values('Echeandía'	, 13 );
insert into ciudad(nombre, id_provincia) values('Caluma'	, 13 );
insert into ciudad(nombre, id_provincia) values('Chimbo'	, 13 );
insert into ciudad(nombre, id_provincia) values('San Miguel'	, 13 );
insert into ciudad(nombre, id_provincia) values('Chillanes'	, 13 );
insert into ciudad(nombre, id_provincia) values('Ambato'	, 14 );
insert into ciudad(nombre, id_provincia) values('Píllaro'	, 14 );
insert into ciudad(nombre, id_provincia) values('Patate'	, 14 );
insert into ciudad(nombre, id_provincia) values('Baños'	, 14 );
insert into ciudad(nombre, id_provincia) values('Pelileo'	, 14 );
insert into ciudad(nombre, id_provincia) values('Cevallos'	, 14 );
insert into ciudad(nombre, id_provincia) values('Tisaleo'	, 14 );
insert into ciudad(nombre, id_provincia) values('Mocha'	, 14 );
insert into ciudad(nombre, id_provincia) values('Quero'	, 14 );
insert into ciudad(nombre, id_provincia) values('Guano'	, 15 );
insert into ciudad(nombre, id_provincia) values('Penipe'	, 15 );
insert into ciudad(nombre, id_provincia) values('Riobamba'	, 15 );
insert into ciudad(nombre, id_provincia) values('Colta'	, 15 );
insert into ciudad(nombre, id_provincia) values('Chambo'	, 15 );
insert into ciudad(nombre, id_provincia) values('Pallatanga'	, 15 );
insert into ciudad(nombre, id_provincia) values('Guamote'	, 15 );
insert into ciudad(nombre, id_provincia) values('Alausí'	, 15 );
insert into ciudad(nombre, id_provincia) values('Cumandá'	, 15 );
insert into ciudad(nombre, id_provincia) values('Chunchi'	, 15 );
insert into ciudad(nombre, id_provincia) values('Palora'	, 16 );
insert into ciudad(nombre, id_provincia) values('Pablo Sexto'	, 16 );
insert into ciudad(nombre, id_provincia) values('Huamboya'	, 16 );
insert into ciudad(nombre, id_provincia) values('Morona'	, 16 );
insert into ciudad(nombre, id_provincia) values('Taisha'	, 16 );
insert into ciudad(nombre, id_provincia) values('Sucúa'	, 16 );
insert into ciudad(nombre, id_provincia) values('Santiago'	, 16 );
insert into ciudad(nombre, id_provincia) values('Logroño'	, 16 );
insert into ciudad(nombre, id_provincia) values('Tiwintza'	, 16 );
insert into ciudad(nombre, id_provincia) values('Limón Indanza'	, 16 );
insert into ciudad(nombre, id_provincia) values('San Juan Bosco'	, 16 );
insert into ciudad(nombre, id_provincia) values('Gualaquiza'	, 16 );
insert into ciudad(nombre, id_provincia) values('El Empalme'	, 17 );
insert into ciudad(nombre, id_provincia) values('Balzar'	, 17 );
insert into ciudad(nombre, id_provincia) values('Colimes'	, 17 );
insert into ciudad(nombre, id_provincia) values('Palestina'	, 17 );
insert into ciudad(nombre, id_provincia) values('Santa Lucía'	, 17 );
insert into ciudad(nombre, id_provincia) values('Pedro Carbo'	, 17 );
insert into ciudad(nombre, id_provincia) values('Isidro Ayora'	, 17 );
insert into ciudad(nombre, id_provincia) values('Lomas de Sargentillo'	, 17 );
insert into ciudad(nombre, id_provincia) values('Nobol'	, 17 );
insert into ciudad(nombre, id_provincia) values('Daule'	, 17 );
insert into ciudad(nombre, id_provincia) values('Salitre'	, 17 );
insert into ciudad(nombre, id_provincia) values('Samborondón'	, 17 );
insert into ciudad(nombre, id_provincia) values('Yaguachi'	, 17 );
insert into ciudad(nombre, id_provincia) values('Alfredo Baquerizo Moreno'	, 17 );
insert into ciudad(nombre, id_provincia) values('Milagro'	, 17 );
insert into ciudad(nombre, id_provincia) values('Simón Bolívar'	, 17 );
insert into ciudad(nombre, id_provincia) values('Naranjito'	, 17 );
insert into ciudad(nombre, id_provincia) values('General Antonio Elizalde'	, 17 );
insert into ciudad(nombre, id_provincia) values('Coronel Marcelino Maridueña'	, 17 );
insert into ciudad(nombre, id_provincia) values('El Triunfo'	, 17 );
insert into ciudad(nombre, id_provincia) values('Durán'	, 17 );
insert into ciudad(nombre, id_provincia) values('Guayaquil'	, 17 );
insert into ciudad(nombre, id_provincia) values('Playas'	, 17 );
insert into ciudad(nombre, id_provincia) values('Naranjal'	, 17 );
insert into ciudad(nombre, id_provincia) values('Balao'	, 17 );
insert into ciudad(nombre, id_provincia) values('Santa Elena' , 18 );
insert into ciudad(nombre, id_provincia) values('La Libertad' , 18 );
insert into ciudad(nombre, id_provincia) values('Salinas' , 18  );
insert into ciudad(nombre, id_provincia) values('La Troncal' , 19 );
insert into ciudad(nombre, id_provincia) values('Cañar'	, 19 );
insert into ciudad(nombre, id_provincia) values('Suscal'	, 19 );
insert into ciudad(nombre, id_provincia) values('El Tambo'	, 19 );
insert into ciudad(nombre, id_provincia) values('Azogues'	, 19 );
insert into ciudad(nombre, id_provincia) values('Biblián'	, 19 );
insert into ciudad(nombre, id_provincia) values('Déleg'	, 19 );
insert into ciudad(nombre, id_provincia) values('Sevilla de Oro'	, 20 );
insert into ciudad(nombre, id_provincia) values('Paute'	, 20 );
insert into ciudad(nombre, id_provincia) values('Guachapala'	, 20 );
insert into ciudad(nombre, id_provincia) values('El Pan'	, 20 );
insert into ciudad(nombre, id_provincia) values('Gualaceo'	, 20 );
insert into ciudad(nombre, id_provincia) values('Chordeleg'	, 20 );
insert into ciudad(nombre, id_provincia) values('Sígsig'	, 20 );
insert into ciudad(nombre, id_provincia) values('Cuenca'	, 20 );
insert into ciudad(nombre, id_provincia) values('Santa Isabel'	, 20 );
insert into ciudad(nombre, id_provincia) values('Pucará'	, 20 );
insert into ciudad(nombre, id_provincia) values('Camilo Ponce Enríquez'	, 20 );
insert into ciudad(nombre, id_provincia) values('San Fernando'	, 20 );
insert into ciudad(nombre, id_provincia) values('Girón'	, 20 );
insert into ciudad(nombre, id_provincia) values('Nabón'	, 20 );
insert into ciudad(nombre, id_provincia) values('Oña'	, 20 );
insert into ciudad(nombre, id_provincia) values('El Guabo'	, 21 );
insert into ciudad(nombre, id_provincia) values('Machala'	, 21 );
insert into ciudad(nombre, id_provincia) values('Pasaje'	, 21 );
insert into ciudad(nombre, id_provincia) values('Chilla'	, 21 );
insert into ciudad(nombre, id_provincia) values('Zaruma'	, 21 );
insert into ciudad(nombre, id_provincia) values('Santa Rosa'	, 21 );
insert into ciudad(nombre, id_provincia) values('Atahualpa'	, 21 );
insert into ciudad(nombre, id_provincia) values('Arenillas'	, 21 );
insert into ciudad(nombre, id_provincia) values('Huaquillas'	, 21 );
insert into ciudad(nombre, id_provincia) values('Las Lajas'	, 21 );
insert into ciudad(nombre, id_provincia) values('Marcabelí'	, 21 );
insert into ciudad(nombre, id_provincia) values('Balsas'	, 21 );
insert into ciudad(nombre, id_provincia) values('Piñas'	, 21 );
insert into ciudad(nombre, id_provincia) values('Portovelo'	, 21 );
insert into ciudad(nombre, id_provincia) values('Saraguro'	, 22 );
insert into ciudad(nombre, id_provincia) values('Loja'	, 22 );
insert into ciudad(nombre, id_provincia) values('Chaguarpamba'	, 22 );
insert into ciudad(nombre, id_provincia) values('Olmedo (Loja)'	, 22 );
insert into ciudad(nombre, id_provincia) values('Catamayo'	, 22 );
insert into ciudad(nombre, id_provincia) values('Paltas'	, 22 );
insert into ciudad(nombre, id_provincia) values('Puyango'	, 22 );
insert into ciudad(nombre, id_provincia) values('Pindal'	, 22 );
insert into ciudad(nombre, id_provincia) values('Celica'	, 22 );
insert into ciudad(nombre, id_provincia) values('Zapotillo'	, 22 );
insert into ciudad(nombre, id_provincia) values('Macará'	, 22 );
insert into ciudad(nombre, id_provincia) values('Sozoranga'	, 22 );
insert into ciudad(nombre, id_provincia) values('Calvas'	, 22 );
insert into ciudad(nombre, id_provincia) values('Gonzanamá'	, 22 );
insert into ciudad(nombre, id_provincia) values('Quilanga'	, 22 );
insert into ciudad(nombre, id_provincia) values('Espíndola'	, 22 );
insert into ciudad(nombre, id_provincia) values('Yacuambi'	, 23 );
insert into ciudad(nombre, id_provincia) values('Yantzaza'	, 23 );
insert into ciudad(nombre, id_provincia) values('El Pangui'	, 23 );
insert into ciudad(nombre, id_provincia) values('Zamora'	, 23 );
insert into ciudad(nombre, id_provincia) values('Centinela del Cóndor'	, 23 );
insert into ciudad(nombre, id_provincia) values('Paquisha'	, 23 );
insert into ciudad(nombre, id_provincia) values('Nangaritza'	, 23 );
insert into ciudad(nombre, id_provincia) values('Palanda'	, 23 );
insert into ciudad(nombre, id_provincia) values('Chinchipe'	, 23 );
insert into ciudad(nombre, id_provincia) values('Isabela'	, 24 );
insert into ciudad(nombre, id_provincia) values('San Cristóbal'	, 24 );
insert into ciudad(nombre, id_provincia) values('Santa Cruz'	, 24 );