insert into provincia values(1,'Esmeraldas');
insert into provincia values(2,'Carchi');
insert into provincia values(3,'Imbabura');
insert into provincia values(4,'Sucumbíos');
insert into provincia values(5,'Manabí');
insert into provincia values(6,'Santo Domingo de los Tsáchilas');
insert into provincia values(7,'Pichincha');
insert into provincia values(8,'Napo');
insert into provincia values(9,'Orellana');
insert into provincia values(10,'Pastaza');
insert into provincia values(11,'Los Ríos');
insert into provincia values(12,'Cotopaxi');
insert into provincia values(13,'Bolívar');
insert into provincia values(14,'Tungurahua');
insert into provincia values(15,'Chimborazo');
insert into provincia values(16,'Morona Santiago');
insert into provincia values(17,'Guayas');
insert into provincia values(18,'Santa Elena');
insert into provincia values(19,'Cañar');
insert into provincia values(20,'Azuay');
insert into provincia values(21,'El Oro');
insert into provincia values(22,'Loja');
insert into provincia values(23,'Zamora Chinchipe');
insert into provincia values(24,'Galápagos');